# Generated by Django 3.2.12 on 2024-01-19 16:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('api', '0003_auto_20240118_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='destinatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 11, 19, 14, 529296)),
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
