# Generated by Django 3.2.12 on 2024-01-19 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20240119_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 13, 4, 35, 98615)),
        ),
        migrations.AlterField(
            model_name='nom_catergoria',
            name='valor',
            field=models.CharField(max_length=50, verbose_name='Valor'),
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=250, verbose_name='Dirección')),
                ('referencia', models.CharField(max_length=250, verbose_name='Referencia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
