# Generated by Django 3.2.12 on 2024-01-19 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240119_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='aprobada',
            field=models.BooleanField(default=False, verbose_name='Se aprobo'),
        ),
        migrations.AddField(
            model_name='factura',
            name='contra_oferta',
            field=models.TextField(blank=True, null=True, verbose_name='Contra oferta'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 16, 0, 19, 257023)),
        ),
    ]
