# Generated by Django 3.2.12 on 2024-01-19 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20240119_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 19, 16, 4, 27, 273630)),
        ),
    ]
