# Generated by Django 3.2.12 on 2024-01-21 22:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20240121_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='es_vendedor',
            new_name='es_proveedor',
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 21, 17, 16, 55, 727971)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(verbose_name='Precio'),
        ),
    ]
