# Generated by Django 3.2.12 on 2024-01-22 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20240122_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenB64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='imagenB64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 14, 50, 23, 228295)),
        ),
    ]
