# Generated by Django 3.2.12 on 2024-01-22 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20240122_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='impuestos_pagados',
            field=models.BooleanField(default=False, verbose_name='Impuestos pagados'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 22, 17, 7, 6, 392445)),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='', null=True, upload_to='imagenes/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_proveedor',
            field=models.BooleanField(default=False, verbose_name='Es proveedor'),
        ),
    ]
